= Animation

Pretty soon, you'll get tired of having just single images displayed on the
screen. Wouldn't it be nice if you could see some animation?

Well, animation is an easy enough idea: after drawing something, erase it and
draw something else. So let's try that; let's make a little puffy diamond
shape.

.Diamond.spin
----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"

PUB Main
    lcd.Start(gfx.Start)

    repeat
        gfx.Sprite(@data1, 0, 0, 0)
        lcd.Draw

        repeat 10000

        gfx.Sprite(@data2, 0, 0, 0)
        lcd.Draw

        repeat 10000
DAT

data1
word    0
word    8, 8
word    %%00011000
word    %%00111100
word    %%01111110
word    %%11111111
word    %%11111111
word    %%01111110
word    %%00111100
word    %%00011000


data2
word    0
word    8, 8
word    %%00000000
word    %%00011000
word    %%00011000
word    %%01111110
word    %%01111110
word    %%00011000
word    %%00011000
word    %%00000000
----

Hey, that wasn't so bad, but that's only two images. Let's try six.

.Star.spin
----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"

PUB Main
    lcd.Start(gfx.Start)

    repeat
        gfx.Sprite(@data1, 0, 0, 0)
        lcd.Draw

        repeat 1000

        gfx.Sprite(@data2, 0, 0, 0)
        lcd.Draw

        repeat 1000

        gfx.Sprite(@data3, 0, 0, 0)
        lcd.Draw

        repeat 1000

        gfx.Sprite(@data4, 0, 0, 0)
        lcd.Draw

        repeat 1000

        gfx.Sprite(@data5, 0, 0, 0)
        lcd.Draw

        repeat 1000

        gfx.Sprite(@data6, 0, 0, 0)
        lcd.Draw

DAT

data1
word    0
word    8, 8
word    %%00000000
word    %%00000000
word    %%00011000
word    %%00111100
word    %%00111100
word    %%00011000
word    %%00000000
word    %%00000000

data2
word    0
word    8, 8
word    %%00000000
word    %%00011000
word    %%00111100
word    %%01100110
word    %%01100110
word    %%00111100
word    %%00011000
word    %%00000000

data3
word    0
word    8, 8
word    %%00011000
word    %%01111110
word    %%01100110
word    %%11000011
word    %%11000011
word    %%01100110
word    %%01111110
word    %%00011000

data4
word    0
word    8, 8
word    %%00011000
word    %%01100110
word    %%01000010
word    %%10000001
word    %%10000001
word    %%01000010
word    %%01100110
word    %%00011000

data5
word    0
word    8, 8
word    %%01100110
word    %%10000001
word    %%10000001
word    %%00000000
word    %%00000000
word    %%10000001
word    %%10000001
word    %%01100110

data6
word    0
word    8, 8
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
----

Hey, that's a fancy animation, but yuck!! What a mess! There's so much code
that it's hard to tell what we're even looking at. That's where frames come
in.

== Animation With Frames


Animation is made much easier with the use of frames. Frames allow us to store
multiple images within the same sprite so that they can be accessed with an
index (0, 1, 2, 3, ...) instead of having to pass the address by name (data1,
data2, data3, ...).

We want to apply this to our previous example. To do so, first, we have to
calculate the ` frameboost ` constant. This value equals the distance in bytes
between two images in a sprite in memory. Here's the formula.

$$
frameboost = width \times height \times bitdepth \times(\frac{1 byte}{8 bits})
$$

Our image is 8 pixels wide and 8 pixel tall, each LameStation color has 2
bits, and there's 8 bits in 1 byte. Therefore, the frameboost for our image is
** 16 ** . Let's add it to the sprite header.

----
word    16
word    8, 8
word    %%00000000
word    %%00000000
word    %%00011000
word    %%00111100
word    %%00111100
word    %%00011000
word    %%00000000
word    %%00000000
----

Next, remember that we're combine all of the images from the previous example
into one sprite, so we will only need one sprite header. So get rid of the
rest of them! Here's what the sprite should look like completed.

----
data
word    16
word    8, 8
word    %%00000000
word    %%00000000
word    %%00011000
word    %%00111100
word    %%00111100
word    %%00011000
word    %%00000000
word    %%00000000

word    %%00000000
word    %%00011000
word    %%00111100
word    %%01100110
word    %%01100110
word    %%00111100
word    %%00011000
word    %%00000000

word    %%00011000
word    %%01111110
word    %%01100110
word    %%11000011
word    %%11000011
word    %%01100110
word    %%01111110
word    %%00011000

word    %%00011000
word    %%01100110
word    %%01000010
word    %%10000001
word    %%10000001
word    %%01000010
word    %%01100110
word    %%00011000

word    %%01100110
word    %%10000001
word    %%10000001
word    %%00000000
word    %%00000000
word    %%10000001
word    %%10000001
word    %%01100110

word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
----

Now we need a way to play the animation. Using `REPEAT`, we can
create a variable `x` and use that to index through the animation from 0 to 5.
Then pass x to gfx.Sprite as the ` frame ` parameter.

----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"

PUB Main | x 
    lcd.Start(gfx.Start)

    repeat
        repeat x from 0 to 5
            gfx.Sprite(@data, 0, 0, x)
            lcd.Draw

            repeat 1000
----

Now look at how much shorter it is, and so much easier to understand!

.StarWithFrames.spin
----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"

PUB Main | x 
    lcd.Start(gfx.Start)

    repeat
        repeat x from 0 to 5
            gfx.Sprite(@data, 0, 0, x)
            lcd.Draw

            repeat 1000
DAT

data
word    16
word    8, 8
word    %%00000000
word    %%00000000
word    %%00011000
word    %%00111100
word    %%00111100
word    %%00011000
word    %%00000000
word    %%00000000

word    %%00000000
word    %%00011000
word    %%00111100
word    %%01100110
word    %%01100110
word    %%00111100
word    %%00011000
word    %%00000000

word    %%00011000
word    %%01111110
word    %%01100110
word    %%11000011
word    %%11000011
word    %%01100110
word    %%01111110
word    %%00011000

word    %%00011000
word    %%01100110
word    %%01000010
word    %%10000001
word    %%10000001
word    %%01000010
word    %%01100110
word    %%00011000

word    %%01100110
word    %%10000001
word    %%10000001
word    %%00000000
word    %%00000000
word    %%10000001
word    %%10000001
word    %%01100110

word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
word    %%00000000
----