= LameGFX and LameLCD

Using the LameStation LCD requires two objects: link:../library/LameLCD.adoc[LameLCD] and link:../library/LameGFX.adoc[LameGFX].

----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"
----

- LameGFX provides functions for drawing different kinds of things.
- LameLCD takes your drawing and outputs it to the actual display.

Think of it like this: LameLCD provides you with a piece of paper, and LameGFX
provides you with various pens and pencils to draw with. That's why these objects are always included together.

Before any drawing, you must start these objects.

----
PUB Main
    lcd.Start(gfx.Start)
----

Now, you can draw to your heart's content, but after drawing, you have to call link:../library/lcd.DrawScreen.adoc[`lcd.DrawScreen`] before you'll actually see anything.

----
    lcd.DrawScreen
----

.Remember This
****
The following is the minimum code needed to initialize and show graphics.

----
OBJ
    lcd : "LameLCD"
    gfx : "LameGFX"

PUB Main
    lcd.Start(gfx.Start)

    ' draw stuff here

    lcd.DrawScreen
----

However, when you run this, you still won't see anything, because you actually
have to draw an image for it to appear on the LCD.
****