= Spin Quick Reference

== Comments

Comments are text that are intended only for the programmer, and ignored by the compiler.

In Spin, Any text following an apostrophe (`'`) on a single line is is a comment, and ignored.

----
x := 5 + y    ' adds 5 and y
----

To span multiple lines, use curly braces (`{`,`}`).

----
{
    This feature adds some awesome capabilities.
    We are using it at full speed here.
}
    newFeature(x, y)
----

== Constants

Constants are named values that cannot change. They work like integers, but if a value is used often enough, using constants makes your code easier to read and modify.

Constants are declared in `CON` blocks.

----
CON
    DOZEN = 12
----

== Variables

Variables are named values that can change. All variables in Spin consist of integers of different sizes.

|===
| *name* | *type* | *unsigned range* | *signed range*
| `byte` | 8-bit integer | 0 - 255 | -128 - 127
| `word` | 16-bit integer | 0 - 65,535 | -32,768 - 32,767
| `long` | 32-bit integer | 0 - 4,294,967,295 | -2,147,483,648 - 2,147,483,647
|===

Variables are created in a `VAR` block. They are initialized to zero by the compiler.

----
VAR
    byte    foo
    word    bar
    long    baz
----

=== Arrays

Spin supports arrays, which store multiple variables as a unit. The size of the array must be declared in advance, with either an integer or a constant defined in a `CON` block.

----
VAR
    byte    donuts[12]
    byte    donuts[DOZEN]
----

You can access the values in arrays with `[]` notation.

----
x := donuts[4]
donuts[6] := 27
----

=== Strings

A string is an array of bytes that is _null-terminated_, or ends in zero.

You can create strings on the fly and use them right away with the `string` keyword.

----
string("Hello world!")
----

Strings can also be declared in `DAT` blocks for reuse, then used with the `@` operator.

----
hellostring     byte    "Hello world!",0
----

== Flow Control

=== If Statements

=== Loops

All loops in Spin use the `REPEAT` command.


== Data

== Functions

