= Spin Quick Reference

== Terms

- Expression - Any combination of symbols that can represent a value.

== Blocks

A feature unique to Spin is the use of _blocks_. Objects can contain six kinds of blocks: `CON`, `VAR`, `PUB`, `PRI`, `OBJ`, and `DAT`. Each block has its own syntax and allowed keywords, like mini-languages in their own right.

== Objects

A file in Spin is called an _object_, and ends with the `.spin` extension.

An object can be written as the main program, or as a _library_ that can be used by other objects.

External objects are declared in an `OBJ` block, and given a unique alias.

----
OBJ
    ser : "LameSerial"
----

Multiple copies of an object can be used.

----
    ser1 : "LameSerial"
    ser2 : "LameSerial"
----

Or an array of objects

----
    ser[4] : "LameSerial"
----

These can be accessed with brackets.

----
PUB Foo
    ser[4].Char("b")
----

== Comments

Comments are text that are intended only for the programmer, and ignored by the compiler.

In Spin, Any text following an apostrophe (`'`) on a single line is is a comment, and ignored.

----
x := 5 + y    ' adds 5 and y
----

To span multiple lines, use curly braces (`{`,`}`).

----
{
    This feature adds some awesome capabilities.
    We are using it at full speed here.
}
    newFeature(x, y)
----

== Operators

The `=` operator sets the value of a constant.

----
VALUE = 10
----

The `:=` operator sets the value of a variable.

----
x := 5
----

=== Arithmetic Operators

You can use basic arithmetic operations. 

----
x := y + z      ' add
x := y - z      ' subtract
x := y * z      ' multiply
x := y / z      ' divide
----

Modulo (`//`) finds the remainder after division.

----
x := y // z
----

You can group expressions using parentheses.

----
x := (y + 4) - (z + 3)
x := ((y + 4) + 4)
----

Decrement (`--`) subtracts one from a value, while increment (`++`) adds one.

----
x++
x--
----

=== Relational Operators

A _relational operator_ tests the relationship between two values. Expressions that use them return a non-zero number if true, or zero if false.

You can test if two values are equal with `==`, or _not_ equal with `<>`.

----
x == y
x <> y
----

You can also test inequality.

----
x < y       ' x is less than y
x > y       ' x is greater than y
x =< y      ' x is equal to or less than y
x => y      ' x is equal to or greater than y
----

=== Logical Operators

Logical operators, or *boolean operators* allow you to create more specific tests in your application.

`AND`:: When both expressions are true, return true.
+
----
x and y
----
`OR`:: When either of the expressions are true, return true.
+
----
x or y
----
`NOT`:: Negate the result of an expression. I.e. if the expression is true, return false; if false, return true.
+
----
x and not y
----

== Constants

Constants are named values that cannot change. They work like integers, but if a value is used often enough, using constants makes your code easier to read and modify.

Constants are declared in `CON` blocks.

----
CON
    DOZEN = 12
----

== Variables

Variables are named values that can change. All variables in Spin consist of integers of different sizes.

|===
| *name* | *type* | *unsigned range* | *signed range*
| `byte` | 8-bit integer | 0 - 255 | -128 - 127
| `word` | 16-bit integer | 0 - 65,535 | -32,768 - 32,767
| `long` | 32-bit integer | 0 - 4,294,967,295 | -2,147,483,648 - 2,147,483,647
|===

Variables are created in a `VAR` block. They are initialized to zero by the compiler.

----
VAR
    byte    foo
    word    bar
    long    baz
----

=== Arrays

Spin supports arrays, which store multiple variables as a unit. The size of the array must be declared in advance, with either an integer or a constant defined in a `CON` block.

----
VAR
    byte    donuts[12]
    byte    donuts[DOZEN]
----

You can access the values in arrays with `[]` notation.

----
x := donuts[4]
donuts[6] := 27
----

=== Strings

A string is an array of bytes that is _null-terminated_, or ends in zero.

You can create strings on the fly and use them right away with the `string` keyword.

----
string("Hello world!")
----

Strings can also be declared in `DAT` blocks for reuse, then used with their address.

----
hellostring     byte    "Hello world!",0
----

== Flow Control

=== Indentation

=== If Statements

=== Loops

All loops in Spin use the `REPEAT` command.


== Data

== Functions

Functions

The first function in an object is 

All Spin objects must have at least one public function.