== Don't Tread On Me

So far, the snake is free to come and go as it pleases, criss-crossing over itself like nobody's business. Well, it's time to put a stop to that. Let's show this snake that there are consequences to dilly-dallying.

The change is simple enough. We want the snake to die if it crosses over itself. This can be accomplished by checking each pixel of the snake to see if it overlaps with the head.

----
            if snakex[i] == snakex[0] and snakey[i] == snakey[0]
----

Then if true, we make sure to tie up all the loose ends, so that the snake starts over fresh.

----
            if snakex[i] == snakex[0] and snakey[i] == snakey[0]
                snakecount := 1
                snakex[0] := 64
                snakey[0] := 32
                snakedir := 1
----

We just need to add it into the loop we've already created that moves the entire snake every frame.

----
        repeat i from snakecount to 1
            if snakex[i] == snakex[0] and snakey[i] == snakey[0]
                snakecount := 1
                snakex[0] := 64
                snakey[0] := 32
                snakedir := 1

            snakex[i] := snakex[i-1]
            snakey[i] := snakey[i-1]
            gfx.Sprite(@dot_gfx, snakex[i], snakey[i], 0)
----

Done. Now your snake will suffer an untimely fate for its carelessness.

View the complete example at `/tutorials/Snake/DontTreadOnMe.spin`.

=== Think about this!

. We wrote code so that the snake dies when it overlaps itself, but why does it die when it reaches the edge of the screen?

// that's because when it can't go any further, it stays put, so the next pixel will come and overlap it on the next frame. This snake essentially has to keep moving or will die.