== Humble beginnings

Okay, now that that's out of the way, let's make the LameStation do something.

Here's a lofty goal: let's make the LameStation draw something. There isn't much to it.

. Add graphics for drawing
. Use graphics to draw screen image
. Send image to actual screen

=== Add graphics for drawing

So here's how that's done. Since snake is just a dot, that's all we need.

----
DAT
    dot_gfx
    word    0
    word    2, 2
    word    %%11
    word    %%11
----

=== Use graphics to draw screen image

Drawing is done with the `gfx.Sprite` command. It has four arguments, which control how it will behave.

.gfx.Sprite
****
> ----
> gfx.Sprite(source, x, y, frame)
> ----

- *source* - the graphics to draw
- *x*, *y* - the position of the graphics (top-left corner)
- *frame* - the number of frames
****

So the source should be the address of the graphics we made before. 

The screen is 128x64 pixels, so you have to draw the dot between (0,0) and (128,64) for it to be visible. Other than that, we don't really care where it shows up yet.

We're not using the frame parameter yet, so just set it to zero.

----
    gfx.Sprite(@dot_gfx, 25, 25, 0)
----

=== Send the image to the screen

If you try running it now, you still won't see anything. You need `lcd.DrawScreen` to actually draw to the screen.

----
    lcd.DrawScreen
----

[WARNING]
.`dot_gfx` does not equal `@dot_gfx`.
====

'@' is the address operator, and it changes the meaning of a variable or label.

- `dot_gfx` is the value at `dot_gfx`.
- `@dot_gfx` is the address of `dot_gfx`, or where it is in memory.

See for yourself. Try removing the '@' symbol from your code and see what happens.
====

At this point, you should have a very exciting dot on the screen.

View the complete example at `/tutorials/Snake/HumbleBeginnings.spin`.