== Leading The March

Two bytes for x and y clearly won't be enough. We have a whole army of pixels that make up this snake, so we're going to need arrays to hold them. We'll want to define one, but first, let's add a constant for the maximum number of snakes. This is important, because without it, it's chaos trying to remember how many are allowed throughout your program.

----
    MAX_SNAKE = 256
----

Now let's trick out the snake variables.

----
    byte    snakex[MAX_SNAKE]
    byte    snakey[MAX_SNAKE]
----

Oh, and one more thing. We need to keep track of how many snake dots there are on the screen.

----
    byte    snakecount
----

In snake, every frame, the snake moves forward one pixel, like this.

----
o o o o o
  o o o o o
    o o o o o
----

So how do we emulate that?

We add this code to test 

----
        if ctrl.A
            if snakecount < constant(MAX_SNAKE-1)
                snakecount++
----

repeat i from 1 to snakecount

----> 

doesn't work

repeat i from snakecount to 1

<----

works

----
o o o o o
 \ \ \ \ \
  o o o o o
----

Going further
****

How could we make this game more efficient? Is it necessary?

----
o o o o o
  | | | |
  o o o o o
----

****

----
    byte    i
----

----
            repeat i from snakecount to 1
                snakex[i] := snakex[i-1]
                snakey[i] := snakey[i-1]
                gfx.Sprite(@dot_gfx, snakex[i], snakey[i], 0) 
----