==  Hello Nothing

Attempting to download an empty file to the LameStation will generate an error from PropellerIDE.

////
- *There must be at least one PUB block*
- *PUB blocks must be uniquely named within a file*
- *The first PUB block in your program is the starting point for your program*
- *I call my first function Main to prevent confusion; there is no other reason*
////

[source, language='pub']
.An empty file.
----

----

so here we see the bare minimum that constitutes a Spin program.

[source, language='pub']
.HelloNothing.spin
----
PUB Main

----

Well, that was easy!

This is called a `PUB` block, which is short for _public function_ . Functions are areas where you write code that can _do stuff_. If your code is a sentence, a function is the verb, the action. You can put as many `PUB` blocks as you want into a file, but when you run your code, the Propeller will start by running the first public function that appears in the file. From that function, you can call other functions.

[source, language='pub']
----
PUB Main
    Third

PUB Another

PUB Third
    Another
----

All Spin programs _must_ include a `PUB` block.

Spin is *not* case-sensitive.
    
[source, language='pub']
----
PUB Main
----

is the same as
    
[source, language='pub']
----
pub main
----

Remember that!


View the complete example at `/tutorials/Basics/HelloNothing.spin`.

=== Bonus Round: Function Names!

Function names can contain letters, numbers, and underscores. However, the first character cannot be a number (_that's good; otherwise, they'd start looking like passwords_).

*Good:*

- `hello_chicken`
- `bacon123`
- `_supertime`

*Bad:*

- `123attack`
- `extreme#@$**`
