= LameMusic

LameMusic is a sequencer for LameAudio that allows your games to play arranged music.

----
music : "LameMusic"
----

Demos for this object can be found in `demos/music/` of the SDK.

== Commands

- `music.Start` - Start the LameMusic song player core.
- `music.Load` - Load a song to play.
- `music.Play` - Play the current song once.
- `music.Loop` - Play the current song forever.
- `music.IsPlaying` - Return whether a song is currently playing.
- `music.Stop` - Stop the currently playing song.

== Usage

To start using LameMusic, call `music.Start` once at the beginning of your program to start the music engine.

Call `music.Load` to load a song, stopping the current song if one was playing. Only one song can play at a time.

You can use the `music.Play` command to play a song once, or `music.Loop` to play it forever. Call `music.IsPlaying` to find out if a song is currently playing.

== Song Format (Advanced)

LameStation songs consist of two main sections: pattern and sequence data.

==== Pattern Data

Patterns contain melodies, riffs, harmonies and any musical parts that fit in a measure.

==== Sequence Data

The sequence defines how the patterns are arranged in time and across channels.

[NOTE]
Software to create LameMusic song files is planned; for now, songs must be created by hand.