= LameControl

LameControl allows you to use the LameStation's joystick and buttons.

----
ctrl : "LameControl"
----

== Commands

- `ctrl.Start` - Initialize the LameControl library.
- `ctrl.Update` - Update the state of all LameStation controls.
- `ctrl.A` - Return the current state of the 'A' button.
- `ctrl.B` - Return the current state of the 'B' button.
- `ctrl.Up` - Return whether the joystick is tilted upwards.
- `ctrl.Right` - Return whether the joystick is tilted to the right.
- `ctrl.Down` - Return whether the joystick is tilted downwards.
- `ctrl.Left` - Return whether the joystick is tilted to the left.

== Description

Before anything else, you must call `ctrl.Start` at the beginning of your program. This tells the Propeller to listen to the controls.

To read the current state of the controls, call `ctrl.Update`. A good place to do this is at the beginning of your main game loop, but it can be called at any time. If this is never called, all other commands will always return false.

----
PUB Main

    repeat
        ctrl.Update
        
        ' more code ...
----