#### lcd.WaitForVerticalSync

Wait until the start of the next LCD frame before continuing.

#####  Syntax

    WaitForVerticalSync

This command takes no parameters and returns no values.

#####  Description

link:lcd.DrawScreen.adoc[lcd.DrawScreen] can be called at any time to copy the drawing buffer to the display buffer. This is likely to happen when LameLCD is already updating the physical screen, which will cause the screen to flicker.

// INSERT IMAGE EXPLAINING THIS.

However, there is a brief period at the start of every LCD cycle where there is no activity. Calling WaitForVerticalSync will force your application to wait until this period before continuing with execution. By calling it before DrawScreen, you can achieve a flicker-free display.

If frame limiting is enabled with link:lcd.SetFrameLimit.adoc[lcd.SetFrameLimit], this command has no effect.

#####  Example

----
PUB Main
    lcd.Start(gfx.Start)

    repeat
        ' draw lots of stuff!!
        lcd.WaitForVerticalSync
        lcd.DrawScreen
----